# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# Validators reject any tx from the mempool with less than the minimum fee per gas.
minimum_fees = ""

# Enable invariant check on mainnet, ignore this config on testnet
check_invariant = false

# Enable track coin flow
track_coin_flow = false

